# -*- coding: utf-8 -*-
"""Experiment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CMyvPJY-8FgbaRW5WGacgwLUwHH-2-XO
"""

a=1
print(type(a))
b='meenu'
print(type(b))
c=[1,2]
print(type(c))
d={1:'kunji',2:'mac'}
print(type(d))
e=True
print(type(e))
f=53.7
print(type(f))
g={"Kunji","Macku"}
print(type(g))
h=(1,2)
print(type(h))
i=bytes()
print(type(i))
j=bytearray()
print(type(j))
k=range(4)
print(type(k))

my_list=['meenu','anu','kunji','ammu']
print(my_list[0])
print(my_list[2])
print(my_list[3])
print(my_list[0:2])
print(my_list[ : ])
print(my_list[-2])

d={1:'meenu',2:'kunji',3:'sree'}
print(d)
print('1st name is '+d[1])
print('4th name is '+d[2])
print(d.keys())
print(d.values())

def add(a,b):
  return a+b
res=add(2,3)
print("sum ", res)

def recfact(n):
  if n==1:
    return n
  else:
    return n*recfact(n-1)
num=7
if num<0:
  print("Factorial not possible...!")
elif num==0:
  print("Factorial of 0 is 1.")
else:
  print("Factorial of ",num," is ",recfact(num))